/* neumACt R&I — Publications page runtime */
(function(){
'use strict';
var S={all:[],type:'',q:'',open:null};
var feed=document.getElementById('blogFeed'), feature=document.getElementById('pubFeatureStage'), hero=document.getElementById('pubHeroMedia'), reader=document.getElementById('articleReader'), count=document.getElementById('filterCount'), archive=document.getElementById('pubArchive'), search=document.getElementById('feedSearch');
function esc(v){return v==null?'':String(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
function txt(v){return String(v||'').replace(/<[^>]*>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/\s+/g,' ').trim();}
function excerpt(v,n){var t=txt(v);return t.length<=n?t:t.slice(0,n).replace(/\s+\S*$/,'')+'…';}
function type(t){if(t==='photo_story')return'highlight';return ['publication','article','update','highlight'].indexOf(t)>-1?t:'article';}
function label(t){var m={publication:['Scientific publication','Publicación científica'],article:['Article','Artículo'],update:['Research update','Actualización'],highlight:['Highlight','Destacado']}[type(t)];return '<span lang="en">'+m[0]+'</span><span lang="es">'+m[1]+'</span>';}
function date(v){if(!v)return'';var d=new Date(v);if(isNaN(d))return'';return '<time datetime="'+d.toISOString().slice(0,10)+'"><span lang="en">'+esc(d.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}))+'</span><span lang="es">'+esc(d.toLocaleDateString('es-ES',{day:'numeric',month:'short',year:'numeric'}))+'</span></time>';}
function year(p){var d=new Date(p.published_at||p.created_at||'');return isNaN(d)?'':String(d.getFullYear());}
function line(p){return p.research_line?'L'+esc(p.research_line.line_number)+' · '+esc(p.research_line.name||''):'';}
function image(p){var a=[];if(p&&p.featured_image_url)a.push(p.featured_image_url);if(p&&Array.isArray(p.image_urls))a=a.concat(p.image_urls);for(var i=0;i<a.length;i++){try{var u=new URL(String(a[i]),location.origin);if(/^https?:$/.test(u.protocol))return esc(u.href);}catch(e){}}return'';}
function doi(v){return String(v||'').trim().replace(/^https?:\/\/(dx\.)?doi\.org\//i,'').replace(/^doi:\s*/i,'');}
function doiLink(v){var d=doi(v);return d?'<a class="pub-doi-link" href="https://doi.org/'+encodeURI(d)+'" target="_blank" rel="noopener">DOI '+esc(d)+' ↗</a>':'';}
function meta(p){var b=[],d=date(p.published_at||p.created_at);if(d)b.push(d);if(p.research_line)b.push('<span>'+line(p)+'</span>');if(type(p.post_type)!=='publication'&&p.author&&p.author.full_name)b.push('<span>'+esc(p.author.full_name)+'</span>');return b.length?'<span class="pub-meta">'+b.join('<span class="pub-meta__sep">·</span>')+'</span>':'';}
function button(p,cls,html){var b=document.createElement('button');b.type='button';b.className=cls;b.innerHTML=html;b.onclick=function(){open(p)};return b;}
function renderHero(){var p=S.all.find(function(x){return x.is_featured&&image(x)})||S.all.find(function(x){return image(x)});if(p&&hero)hero.innerHTML='<img src="'+image(p)+'" alt="" fetchpriority="high"><div class="pub-hero__scrim"></div>';}
function renderFeature(){if(!feature)return;if(!S.all.length){feature.innerHTML='<div class="pub-empty"><span lang="en">No public items are available yet.</span><span lang="es">Todavía no hay contenidos públicos disponibles.</span></div>';return;}var p=S.all.find(function(x){return x.is_featured})||S.all[0], t=type(p.post_type), img=image(p), side=S.all.filter(function(x){return x.id!==p.id}).slice(0,2), g=document.createElement('div');g.className='pub-feature-grid';feature.innerHTML='';g.appendChild(button(p,'pub-feature-lead','<span class="pub-feature-lead__media '+(img?'':'is-empty')+'">'+(img?'<img src="'+img+'" alt="'+esc(p.title||'')+'">':'')+'</span><span class="pub-feature-lead__copy"><span class="pub-object-label">'+label(t)+'</span><span class="pub-feature-lead__title">'+esc(p.title||'Untitled')+'</span>'+(t==='publication'?(p.authors_text?'<span class="pub-feature-lead__excerpt">'+esc(p.authors_text)+'</span>':''):(p.body?'<span class="pub-feature-lead__excerpt">'+esc(excerpt(p.body,220))+'</span>':''))+meta(p)+'<span class="pub-item__open"><span lang="en">Open</span><span lang="es">Abrir</span> →</span></span>'));if(side.length){var r=document.createElement('div');r.className='pub-feature-rail';side.forEach(function(x){r.appendChild(button(x,'pub-feature-secondary','<span class="pub-object-label">'+label(x.post_type)+'</span><span class="pub-feature-secondary__title">'+esc(x.title||'Untitled')+'</span>'+meta(x)+'<span class="pub-feature-secondary__arrow">↗</span>'))});g.appendChild(r)}feature.appendChild(g);}
function item(p){var t=type(p.post_type),img=image(p),h='';if(t==='publication')h='<span class="pub-item__kind">'+label(t)+'</span><span class="pub-publication__main"><span class="pub-publication__title">'+esc(p.title||'Untitled')+'</span>'+(p.authors_text?'<span class="pub-publication__authors">'+esc(p.authors_text)+'</span>':'')+'<span class="pub-publication__journal">'+esc(p.journal_name||'')+(p.journal_name&&year(p)?' · ':'')+esc(year(p))+'</span>'+(p.research_line?'<span class="pub-publication__line">'+line(p)+'</span>':'')+'</span><span class="pub-publication__actions">'+(p.doi?'<span class="pub-doi-static">DOI '+esc(doi(p.doi))+'</span>':'')+'<span class="pub-item__arrow">→</span></span>';else if(t==='update')h='<span class="pub-update__date">'+date(p.published_at||p.created_at)+'</span><span class="pub-update__copy"><span class="pub-object-label">'+label(t)+'</span><span class="pub-update__title">'+esc(p.title||'Untitled')+'</span>'+(p.body?'<span class="pub-update__excerpt">'+esc(excerpt(p.body,180))+'</span>':'')+(p.research_line?'<span class="pub-update__line">'+line(p)+'</span>':'')+'</span><span class="pub-item__arrow">→</span>';else h=(img?'<span class="pub-card__media"><img src="'+img+'" alt="'+esc(p.title||'')+'" loading="lazy"></span>':'')+'<span class="pub-card__copy"><span class="pub-object-label">'+label(t)+'</span><span class="pub-card__title">'+esc(p.title||'Untitled')+'</span>'+(p.body?'<span class="pub-card__excerpt">'+esc(excerpt(p.body,t==='article'?190:170))+'</span>':'')+meta(p)+'<span class="pub-item__open"><span lang="en">Open</span><span lang="es">Abrir</span> →</span></span>';return button(p,'pub-item pub-item--'+t+(img?' has-media':' no-media'),h);}
function filtered(){var q=S.q.toLowerCase();return S.all.filter(function(p){if(S.type&&type(p.post_type)!==S.type)return false;if(!q)return true;return [p.title,p.body,p.authors_text,p.journal_name,p.doi,p.author&&p.author.full_name,p.research_line&&p.research_line.name].filter(Boolean).join(' ').toLowerCase().indexOf(q)>-1;});}
function renderFeed(){if(!feed)return;var a=filtered();feed.innerHTML='';if(count)count.innerHTML='<span lang="en">'+a.length+' '+(a.length===1?'item':'items')+'</span><span lang="es">'+a.length+' '+(a.length===1?'resultado':'resultados')+'</span>';if(!a.length){feed.innerHTML='<div class="pub-empty"><strong><span lang="en">No matching publications</span><span lang="es">No hay publicaciones coincidentes</span></strong><br><span lang="en">Try another category or search term.</span><span lang="es">Pruebe otra categoría o término.</span></div>';return;}var f=document.createDocumentFragment();a.forEach(function(p){f.appendChild(item(p))});feed.appendChild(f);}
function renderArchive(){if(!archive)return;var y={};S.all.forEach(function(p){var k=year(p);if(k)y[k]=(y[k]||0)+1});var ks=Object.keys(y).sort(function(a,b){return b-a});if(S.all.length<6||ks.length<2){archive.hidden=true;return;}archive.hidden=false;archive.innerHTML='<div><p class="pub-section-label"><span lang="en">Archive</span><span lang="es">Archivo</span></p><p class="pub-archive__copy"><span lang="en">Output by publication year.</span><span lang="es">Producción por año.</span></p></div><div class="pub-archive__years">'+ks.map(function(k){return'<span class="pub-archive__year"><strong>'+k+'</strong><span>'+y[k]+'</span></span>'}).join('')+'</div>';}
function safeBody(v){if(!v)return'';var s=txt(v);return String(v).indexOf('<')>-1?'<p>'+esc(s)+'</p>':String(v).split(/\n{2,}/).map(function(p){return'<p>'+esc(p.trim())+'</p>'}).join('');}
function setUrl(id,replace){var u=new URL(location.href);if(id)u.searchParams.set('post',id);else u.searchParams.delete('post');history[replace?'replaceState':'pushState']({post:id||null},'',u.pathname+u.search+u.hash);}
function open(p,fromPop){if(!reader)return;var t=type(p.post_type),img=image(p),body=safeBody(p.body);reader.innerHTML='<div class="pub-reader" role="dialog" aria-modal="true"><div class="pub-reader__topbar"><span class="pub-reader__brand">neumACt · <span lang="en">Publications</span><span lang="es">Publicaciones</span></span><button class="pub-reader__back" id="pubReaderBack">← <span lang="en">Back to publications</span><span lang="es">Volver a publicaciones</span></button></div><article class="pub-reader__article"><header class="pub-reader__header"><div class="pub-object-label">'+label(t)+'</div><h1>'+esc(p.title||'Untitled')+'</h1>'+(t==='publication'?'<div class="pub-reader__bibliography">'+(p.authors_text?'<p>'+esc(p.authors_text)+'</p>':'')+(p.journal_name?'<p class="pub-reader__journal">'+esc(p.journal_name)+(year(p)?' · '+year(p):'')+'</p>':'')+(p.doi?doiLink(p.doi):'')+'</div>':'')+'<div class="pub-reader__meta">'+date(p.published_at||p.created_at)+(p.research_line?'<span>·</span><span>'+line(p)+'</span>':'')+(t!=='publication'&&p.author&&p.author.full_name?'<span>·</span><span>'+esc(p.author.full_name)+'</span>':'')+'</div></header>'+(img?'<figure class="pub-reader__cover"><img src="'+img+'" alt="'+esc(p.title||'')+'"></figure>':'')+(body?'<div class="pub-reader__body">'+body+'</div>':'')+'</article></div>';document.body.classList.add('pub-reader-open');S.open=String(p.id);document.getElementById('pubReaderBack').onclick=function(){close(false)};if(!fromPop)setUrl(p.id,false);}
function close(fromPop){if(!reader)return;reader.innerHTML='';document.body.classList.remove('pub-reader-open');S.open=null;if(!fromPop)setUrl(null,false);}
function urlState(){var id=new URL(location.href).searchParams.get('post');if(!id){if(S.open)close(true);return;}var p=S.all.find(function(x){return String(x.id)===id});if(p&&S.open!==id)open(p,true);}
function schema(){var old=document.getElementById('pubSchema');if(old)old.remove();var a=S.all.filter(function(p){return type(p.post_type)==='publication'});if(!a.length)return;var s=document.createElement('script');s.id='pubSchema';s.type='application/ld+json';s.textContent=JSON.stringify({'@context':'https://schema.org','@graph':a.map(function(p){var x={'@type':'ScholarlyArticle',headline:p.title||''};if(p.authors_text)x.author=p.authors_text.split(/,\s*/).map(function(n){return{'@type':'Person',name:n}});if(p.published_at)x.datePublished=String(p.published_at).slice(0,10);if(p.journal_name)x.isPartOf={'@type':'Periodical',name:p.journal_name};if(p.doi)x.sameAs='https://doi.org/'+doi(p.doi);return x})});document.head.appendChild(s);}
document.querySelectorAll('.pub-filter').forEach(function(b){b.onclick=function(){S.type=b.dataset.type||'';document.querySelectorAll('.pub-filter').forEach(function(x){x.classList.toggle('is-active',x===b)});renderFeed();}});if(search)search.oninput=function(){S.q=search.value||'';renderFeed();};document.onkeydown=function(e){if(e.key==='Escape'&&S.open)close(false)};addEventListener('popstate',urlState);
window.onNewsLoaded=function(){S.all=Array.isArray(window._newsAllPosts)?window._newsAllPosts.slice():[];renderHero();renderFeature();renderFeed();renderArchive();schema();urlState();};if(window._newsAllPosts&&window._newsAllPosts.length)window.onNewsLoaded();
})();
